Repository adevinta/spark-ios, pull requests merged in 2023-11, with the labels that each got.

#586 [Badge-572] Removed old snapshots. Fix rescaling when text changes.
  core/Sources/Components/Badge/View/SwiftUI/BadgeViewSnapshotTests.swift
  core/Sources/Components/Badge/View/UIKit/BadgeUIView.swift
  core/Sources/Components/Badge/View/UIKit/BadgeUIViewSnapshotTests.swift
  core/Sources/Components/Badge/ViewModel/BadgeViewModel.swift
  spark/Demo/Classes/View/Components/Badge/SwiftUI/BadgeComponentView.swift
  spark/Demo/Classes/View/Components/Badge/UIKit/BadgeComponentUIView.swift
  spark/Demo/Classes/View/Components/Badge/UIKit/BadgeComponentUIViewModel.swift
Labels: Bug

#601 [TextField#278] TextField scalability
  core/Sources/Components/TextField/StandaloneTextField/UIKit/TextFieldUIView.swift
  spark/Demo/Classes/View/Components/TextField/UIKit/TextFieldComponentUIView.swift
  spark/Demo/TextFieldUIViewController.swift
Labels: ✅ Ready, UIKit

#603 [Checkbox#473] Design changes
  core/Sources/Components/Checkbox/Enum/CheckboxAlignment.swift
  core/Sources/Components/Checkbox/Enum/CheckboxIntent.swift
  core/Sources/Components/Checkbox/Enum/SelectButtonState.swift
  core/Sources/Components/Checkbox/Model/CheckboxColors.swift
  core/Sources/Components/Checkbox/Model/CheckboxGroupItemProtocol.swift
  core/Sources/Components/Checkbox/Model/CheckboxViewModel.swift
  core/Sources/Components/Checkbox/Model/CheckboxViewModelTests.swift
  core/Sources/Components/Checkbox/Properties/Internal/CheckboxColorables.swift
  core/Sources/Components/Checkbox/Properties/Internal/CheckboxStateColors.swift
  core/Sources/Components/Checkbox/UseCase/CheckboxGetSpacingUseCase.swift
  core/Sources/Components/Checkbox/UseCase/CheckboxGetSpacingUseCaseTests.swift
  core/Sources/Components/Checkbox/UseCase/Colors/CheckboxColorsUseCase.swift
  core/Sources/Components/Checkbox/UseCase/Colors/CheckboxColorsUseCaseTests.swift
  core/Sources/Components/Checkbox/UseCase/IntentColors/CheckboxStateColorsUseCase.swift
  core/Sources/Components/Checkbox/UseCase/IntentColors/CheckboxStateColorsUseCaseTests.swift
  core/Sources/Components/Checkbox/View/CheckboxGroupItemDefault.swift
  core/Sources/Components/Checkbox/View/CheckboxViewModel.swift
  core/Sources/Components/Checkbox/View/CheckboxViewModelTests.swift
  core/Sources/Components/Checkbox/View/SwiftUI/CheckboxGroupView.swift
  core/Sources/Components/Checkbox/View/SwiftUI/CheckboxGroupViewSnapshotTests.swift
  core/Sources/Components/Checkbox/View/SwiftUI/CheckboxView.swift
  core/Sources/Components/Checkbox/View/SwiftUI/CheckboxViewSnapshotTests.swift
  core/Sources/Components/Checkbox/View/UIKit/CheckboxControlUIView.swift
  core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIView.swift
  core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIViewActionTests.swift
  core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIViewDelegate.swift
  core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIViewSnapshotTests.swift
  core/Sources/Components/Checkbox/View/UIKit/CheckboxUIView.swift
  core/Sources/Components/Checkbox/View/UIKit/CheckboxUIViewActionTests.swift
  core/Sources/Components/Checkbox/View/UIKit/CheckboxUIViewSnapshotTests.swift
  core/Sources/Components/SelectButton/Enum/SelectButtonState.swift
  spark/Demo/Classes/DemoIconography.swift
  spark/Demo/Classes/View/Components/Badge/SwiftUI/BadgeComponentView.swift
  spark/Demo/Classes/View/Components/Badge/UIKit/BadgeComponentUIView.swift
  spark/Demo/Classes/View/Components/Button/SwiftUI/ButtonComponentView.swift
  spark/Demo/Classes/View/Components/Checkbox/CheckboxViewModel.swift
  spark/Demo/Classes/View/Components/Checkbox/ComponentsCheckboxListView.swift
  spark/Demo/Classes/View/Components/Checkbox/SwiftUI/CheckboxGroupView.swift
  spark/Demo/Classes/View/Components/Checkbox/SwiftUI/CheckboxView.swift
  spark/Demo/Classes/View/Components/Checkbox/UIKit/Checkbox/CheckboxComponentUIView.swift
  spark/Demo/Classes/View/Components/Checkbox/UIKit/Checkbox/CheckboxComponentUIViewController.swift
  spark/Demo/Classes/View/Components/Checkbox/UIKit/Checkbox/CheckboxComponentUIViewModel.swift
  spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroup/CheckboxGroupComponentUIView.swift
  spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroup/CheckboxGroupComponentUIViewController.swift
  spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroup/CheckboxGroupComponentUIViewModel.swift
  spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroupViewController.swift
  spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxViewController.swift
  spark/Demo/Classes/View/Components/Chip/SwiftUI/ChipComponentView.swift
  spark/Demo/Classes/View/Components/Main/ComponentUIView.swift
  spark/Demo/Classes/View/Components/Main/Configuration/UIKit/Item/ComponentsConfigurationItemUIType.swift
  spark/Demo/Classes/View/Components/Main/Configuration/UIKit/Item/ComponentsConfigurationItemView.swift
  spark/Demo/Classes/View/Components/Main/Configuration/UIKit/Item/ComponentsConfigurationItemViewModel.swift
  spark/Demo/Classes/View/Components/ProgressBar/Indeterminate/SwiftUI/ProgressBarIndeterminateComponentView.swift
  spark/Demo/Classes/View/Components/Switch/SwiftUI/SwitchComponentView.swift
  spark/Demo/Classes/View/Components/Tab/SwiftUI/TabComponent.swift
Labels: ✅ Ready

#575 [RadioButton#449] Design update
  core/Sources/Components/RadioButton/Enum/RadioButtonIntent.swift
  core/Sources/Components/RadioButton/Enum/RadioButtonLabelPosition.swift
  core/Sources/Components/RadioButton/Enum/RadioButtonState.swift
  core/Sources/Components/RadioButton/Properties/Internal/RadioButtonAttributes.swift
  core/Sources/Components/RadioButton/Properties/Internal/RadioButtonColors.swift
  core/Sources/Components/RadioButton/Properties/Internal/RadioButtonGroupContent.swift
  core/Sources/Components/RadioButton/Properties/Internal/RadioButtonStateAttribute.swift
  core/Sources/Components/RadioButton/UseCases/GetRadioButtonColorsUseCase.swift
  core/Sources/Components/RadioButton/UseCases/GetRadioButtonColorsUseCaseTests.swift
  core/Sources/Components/RadioButton/UseCases/GetRadioButtonGroupColorUseCase.swift
  core/Sources/Components/RadioButton/UseCases/GetRadioButtonGroupColorUseCaseTests.swift
  core/Sources/Components/RadioButton/UseCases/RadioButtonGetAttributesUseCase.swift
  core/Sources/Components/RadioButton/UseCases/RadioButtonGetAttributesUseCaseTests.swift
  core/Sources/Components/RadioButton/UseCases/RadioButtonGetColorsUseCase.swift
  core/Sources/Components/RadioButton/UseCases/RadioButtonGetColorsUseCaseTests.swift
  core/Sources/Components/RadioButton/UseCases/RadioButtonGetGroupColorUseCase.swift
  core/Sources/Components/RadioButton/UseCases/RadioButtonGetGroupColorUseCaseTests.swift
  core/Sources/Components/RadioButton/View/RadioButtonGroupViewModel.swift
  core/Sources/Components/RadioButton/View/RadioButtonGroupViewModelTests.swift
  core/Sources/Components/RadioButton/View/RadioButtonViewModel.swift
  core/Sources/Components/RadioButton/View/RadioButtonViewModelTests.swift
  core/Sources/Components/RadioButton/View/SwiftUI/RadioButtonGroupView.swift
  core/Sources/Components/RadioButton/View/SwiftUI/RadioButtonGroupViewSnapshotTests.swift
  core/Sources/Components/RadioButton/View/SwiftUI/RadioButtonView.swift
  core/Sources/Components/RadioButton/View/SwiftUI/RadioButtonViewSnapshotTests.swift
  core/Sources/Components/RadioButton/View/UIKit/RadioButtonToggleUIViewSnapshotTests.swift
  core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIGroupView.swift
  core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIGroupViewSnapshotTests.swift
  core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIView.swift
  core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIViewSnapshotTests.swift
  spark/Demo/Classes/Helper/NSAttributedStringBuilder.swift
  spark/Demo/Classes/View/Components/Chip/SwiftUI/ChipComponentView.swift
  spark/Demo/Classes/View/Components/ComponentsView.swift
  spark/Demo/Classes/View/Components/ComponentsViewController.swift
  spark/Demo/Classes/View/Components/Main/ComponentUIView.swift
  spark/Demo/Classes/View/Components/Main/Configuration/SwiftUI/Checkbox.swift
  spark/Demo/Classes/View/Components/RadioButton/SwiftUI/RadioButtonComponent.swift
  spark/Demo/Classes/View/Components/RadioButton/SwiftUI/RadioButtonGroup.swift
  spark/Demo/Classes/View/Components/RadioButton/UIKit/RadioButtonComponentUIView.swift
  spark/Demo/Classes/View/Components/RadioButton/UIKit/RadioButtonComponentUIViewController.swift
  spark/Demo/Classes/View/Components/RadioButton/UIKit/RadioButtonComponentUIViewModel.swift
  spark/Demo/Classes/View/Components/RadioButton/UIKit/RadioButtonUIGroup.swift
Labels: Testing

#612 [Rating#589] Single star view
  core/Sources/Components/Rating/Cache/CGLayerCache.swift
  core/Sources/Components/Rating/Enum/StarFillMode.swift
  core/Sources/Components/Rating/Enum/StarFillModeUnitTests.swift
  core/Sources/Components/Rating/Graphics/ShapeLayer.swift
  core/Sources/Components/Rating/Graphics/Star.swift
  core/Sources/Components/Rating/Model/StarConfiguration.swift
  core/Sources/Components/Rating/View/UIKit/StarUIView.swift
  core/Sources/Components/Rating/View/UIKit/StarUIViewTests.swift
  spark/Demo/Classes/View/Components/ComponentsViewController.swift
  spark/Demo/Classes/View/Components/Rating/UIKit/StarComponentUIView.swift
  spark/Demo/Classes/View/Components/Rating/UIKit/StarComponentUIViewModel.swift
  spark/Demo/Classes/View/Components/Rating/UIKit/StarComponentViewController.swift
Labels: ✅ Ready

#616 [Rating#590] Add use case to calculate color
  core/Sources/Components/Rating/Enum/RatingIntent.swift
  core/Sources/Components/Rating/Model/RatingColors.swift
  core/Sources/Components/Rating/Model/RatingState.swift
  core/Sources/Components/Rating/UseCases/RatingGetColorsUseCase.swift
  core/Sources/Components/Rating/UseCases/RatingGetColorsUseCaseUnitTests.swift
  spark/Demo/Classes/View/Components/Main/Configuration/SwiftUI/Checkbox.swift
Labels: ✅ Ready

#628 [Checkbox#627] Fix state parameter.
  spark/Demo/Classes/View/Components/Button/SwiftUI/ButtonComponentView.swift
  spark/Demo/Classes/View/Components/Main/Configuration/SwiftUI/Checkbox.swift
Labels: ✅ Ready

#632 [Checkbox#630] Fix publisher initliazer issue
  core/Sources/Components/Checkbox/View/UIKit/CheckboxUIView.swift
Labels: ✅ Ready

#631 [Demo-629] Fix value received from checkbox.
  spark/Demo/Classes/Helper/AnyIsTrue.swift
  spark/Demo/Classes/View/Components/Chip/UIKit/ChipComponentUIViewModel.swift
  spark/Demo/Classes/View/Components/Main/Configuration/UIKit/Item/ComponentsConfigurationItemView.swift
  spark/Demo/Classes/View/Components/RadioButton/UIKit/RadioButtonComponentUIViewModel.swift
  spark/Demo/Classes/View/Components/Tab/UIKit/TabComponentUIViewModel.swift
Labels: ✅ Ready, DemoApp

#602 [TextField#278] Merge feature branch into main
  core/Sources/Components/TextField/AddOnTextField/Model/AddOnTextFieldViewModel.swift
  core/Sources/Components/TextField/AddOnTextField/Model/AddOnTextFieldViewModelTests.swift
  core/Sources/Components/TextField/AddOnTextField/UIKit/AddOnTextFieldUIView.swift
  core/Sources/Components/TextField/Enum/TextFieldBorderStyle.swift
  core/Sources/Components/TextField/Enum/TextFieldIntent.swift
  core/Sources/Components/TextField/Model/TextFieldBorders.swift
  core/Sources/Components/TextField/Model/TextFieldColors.swift
  core/Sources/Components/TextField/Model/TextFieldSpacings.swift
  core/Sources/Components/TextField/StandaloneTextField/Model/TextFieldUIViewModel.swift
  core/Sources/Components/TextField/StandaloneTextField/Model/TextFieldUIViewModelTests.swift
  core/Sources/Components/TextField/StandaloneTextField/UIKit/TextFieldUIView.swift
  core/Sources/Components/TextField/UseCase/TextFieldGetBordersUseCase.swift
  core/Sources/Components/TextField/UseCase/TextFieldGetBordersUseCaseTests.swift
  core/Sources/Components/TextField/UseCase/TextFieldGetColorsUseCase.swift
  core/Sources/Components/TextField/UseCase/TextFieldGetColorsUseCaseTests.swift
  core/Sources/Components/TextField/UseCase/TextFieldGetSpacingsUseCase.swift
  core/Sources/Components/TextField/UseCase/TextFieldGetSpacingsUseCaseTests.swift
  spark/Demo/Classes/View/Components/ComponentsViewController.swift
  spark/Demo/Classes/View/Components/TextField/SwitftUI/TextFieldComponentView.swift
  spark/Demo/Classes/View/Components/TextField/UIKit/TextFieldComponentUIView.swift
  spark/Demo/Classes/View/Components/TextField/UIKit/TextFieldComponentUIViewModel.swift
  spark/Demo/TextFieldUIViewController.swift
Labels: ✅ Ready, UIKit, Component

#640 [Checkbox#619] Fix halo color
  core/Sources/Components/Checkbox/UseCase/Colors/CheckboxColorsUseCase.swift
  core/Sources/Components/Checkbox/UseCase/Colors/CheckboxColorsUseCaseTests.swift
  core/Sources/Components/Checkbox/View/UIKit/CheckboxControlUIView.swift
Labels: Testing
