Repository adevinta/spark-ios, pull requests merged in 2024-01, with the labels that each got.

#716 [Bug#715] Fix updating disabled state when dynamic sizes change.
  core/Sources/Common/SwiftUI/View/DoAction.swift
  core/Sources/Common/SwiftUI/View/IsEnabledModifier.swift
  core/Sources/Components/Chip/View/SwiftUI/ChipView.swift
  core/Sources/Components/RadioButton/View/SwiftUI/RadioButtonView.swift
  core/Sources/Components/Tab/View/SwiftUI/TabItemView.swift
  core/Sources/Components/Tab/ViewModel/TabItemViewModel.swift
Labels: Bug, ✅ Ready

#689 [RadioButton#688] Don't publish value from binding.
  core/Sources/Common/Combine/Publisher/PublishingBinding.swift
  core/Sources/Common/Combine/Publisher/ValueBinding.swift
  core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIGroupView.swift
  core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIView.swift
  spark/Demo/Classes/View/Components/RadioButton/UIKit/RadioButtonComponentUIView.swift
Labels: Testing

#712 [Checkbox#711] Added support for value changed to checkbox and group.
  core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIView.swift
  core/Sources/Components/Checkbox/View/UIKit/CheckboxUIView.swift
  spark/Demo/Classes/Tabbar/ConsoleView.swift
  spark/Demo/Classes/View/Components/Checkbox/UIKit/Checkbox/CheckboxComponentUIView.swift
  spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroup/CheckboxGroupComponentUIView.swift
Labels: Testing

#718 [Tab#717] Fix rescaling issue.
  core/Sources/Components/Tab/View/SwiftUI/TabView.swift
Labels: Testing

#728 [DemoApp#727] Fix constraint bug
  spark/Demo/Classes/View/Components/Main/ComponentUIView.swift
Labels: ✅ Ready

#673 [RatingInput#672] Rating Input SwiftUI
  core/Sources/Common/Foundation/Extension/CGRect-Location.swift
  core/Sources/Common/Foundation/Extension/CGRectLocationTests.swift
  core/Sources/Common/Foundation/Extension/UIView-Closest.swift
  core/Sources/Components/Rating/View/RatingDisplayViewModel.swift
  core/Sources/Components/Rating/View/SwiftUI/RatingInputView.swift
  core/Sources/Components/Rating/View/SwiftUI/RatingInputViewSnapshotTests.swift
  core/Sources/Components/Rating/View/SwiftUI/StarView.swift
  spark/Demo/Classes/View/Components/ComponentsView.swift
  spark/Demo/Classes/View/Components/Rating/SwiftUI/RatingInputComponent.swift
Labels: SwiftUI, Testing

#677 [Slider#204] Added snapshot tests + corrected CGColor not updating on traitCollectionDidChange + added comments on functions using CGLayers like applyShadow
  core/Sources/Common/UIKit/Extension/UIView/UIView+LayerExtension.swift
  core/Sources/Components/Slider/Handle/View/SliderHandle.swift
  core/Sources/Components/Slider/Handle/View/SliderHandleUIControl.swift
  core/Sources/Components/Slider/Handle/ViewModel/SliderHandleViewModel.swift
  core/Sources/Components/Slider/UseCase/GetClosestValue/SliderGetClosestValueInBoundsUseCase.swift
  core/Sources/Components/Slider/UseCase/GetClosestValue/SliderGetClosestValueUseCasableMock+Tests.swift
  core/Sources/Components/Slider/UseCase/GetClosestValue/SliderGetClosestValueUseCase.swift
  core/Sources/Components/Slider/UseCase/GetClosestValue/SliderGetClosestValueUseCaseTests.swift
  core/Sources/Components/Slider/UseCase/GetStepValues/SliderGetStepValuesInBoundsUseCasableMock+Tests.swift
  core/Sources/Components/Slider/UseCase/GetStepValues/SliderGetStepValuesInBoundsUseCase.swift
  core/Sources/Components/Slider/UseCase/GetStepValues/SliderGetStepValuesInBoundsUseCaseTests.swift
  core/Sources/Components/Slider/View/Slider.swift
  core/Sources/Components/Slider/View/SliderScenario+SnapshotTests.swift
  core/Sources/Components/Slider/View/SliderUIControl.swift
  core/Sources/Components/Slider/View/SliderUIControlSnapshotTests.swift
  core/Sources/Components/Slider/ViewModel/Base/SliderViewModel.swift
  core/Sources/Components/Slider/ViewModel/Base/SliderViewModelTests.swift
  core/Sources/Components/Slider/ViewModel/Base/SliderViewModelWithMocksTests.swift
  core/Sources/Components/Slider/ViewModel/Single/SingleSiderViewModel.swift
  core/Sources/Components/Slider/ViewModel/Single/SingleSliderViewModel.swift
  core/Sources/Components/Slider/ViewModel/Single/SingleSliderViewModelTests.swift
  core/Sources/Theming/Content/Elevation/Shadow/UIView+ElevationShadow.swift
  spark/Demo/Classes/View/Components/ComponentsView.swift
  spark/Demo/Classes/View/Components/Slider/SwiftUI/SliderComponentView.swift
  spark/Demo/Classes/View/Components/Slider/UIKit/SliderComponentUIControl.swift
Labels: Component, Draft

#745 [Checkbox#744] Fix intent initiliaze and empty text issue
  core/Sources/Components/Checkbox/View/UIKit/CheckboxUIView.swift
Labels: Testing

#732 [RatingDisplay#731] Added size 24px.
  core/Sources/Components/Rating/Enum/RatingDisplaySize.swift
  core/Sources/Components/Rating/TestHelpers/RatingDisplayScenarioSnapshotTests.swift
  core/Sources/Components/Rating/UseCases/RatingSizeAttributesUseCase.swift
  core/Sources/Components/Rating/UseCases/RatingSizeAttributesUseCaseTests.swift
Labels: ✅ Ready
