Repository adevinta/spark-ios, pull requests merged in 2024-05, with the labels that each got.

#898 [RatingInput#897] Rating display update disabled
  core/Sources/Components/Rating/View/RatingDisplayViewModel.swift
  core/Sources/Components/Rating/View/SwiftUI/RatingInputView.swift
Labels: Blocked

#892 [Formfield#859] Add snapshots
  core/Sources/Components/FormField/AccessibilityIdentifier/FormFieldAccessibilityIdentifier.swift
  core/Sources/Components/FormField/TestHelper/FormfieldConfigurationSnapshotTests.swift
  core/Sources/Components/FormField/TestHelper/FormfieldScenarioSnapshotTests.swift
  core/Sources/Components/FormField/View/SwiftUI/FormFieldView.swift
  core/Sources/Components/FormField/View/SwiftUI/FormFieldViewSnapshotTests.swift
  core/Sources/Components/FormField/View/UIKit/FormFieldUIView.swift
  core/Sources/Components/FormField/View/UIKit/FormFieldUIViewSnapshotTests.swift
Labels: ✅ Ready

#965 [Bug#963] Fixed addon containers not hidden at init
  core/Sources/Components/TextField/Addons/View/UIKit/TextFieldAddonsUIView.swift
Labels: Next Release Candidate

#966 [Bug#964] Fixed layout issue with addons taking priority over textfield
  core/Sources/Components/TextField/Addons/View/UIKit/TextFieldAddonsUIView.swift
Labels: Next Release Candidate

#973 [Button-972] Fix button animation
  core/Sources/Components/Button/View/SwiftUI/Internal/ButtonContainerView.swift
  core/Sources/Components/Button/View/SwiftUI/Public/Button/ButtonView.swift
Labels: Next Release Candidate

#975 Fix TextFieldAddons
  core/Sources/Components/TextField/Addons/View/UIKit/TextFieldAddonsUIView.swift
Labels: Next Release Candidate

#979 Component/checkbox bug
  core/Sources/Components/Checkbox/AccessibilityIdentifier/CheckboxAccessibilityIdentifier.swift
  core/Sources/Components/Checkbox/Model/CheckboxGroupViewModel.swift
  core/Sources/Components/Checkbox/Model/CheckboxGroupViewModelTests.swift
  core/Sources/Components/Checkbox/View/SwiftUI/CheckboxGroupView.swift
  core/Sources/Components/Checkbox/View/SwiftUI/CheckboxView.swift
  core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIView.swift
  core/Sources/Components/Checkbox/View/UIKit/CheckboxUIView.swift
  spark/Demo/Classes/View/Components/Checkbox/SwiftUI/CheckboxGroupView.swift
  spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroup/CheckboxGroupComponentUIView.swift
  spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroup/CheckboxGroupComponentUIViewModel.swift
Labels: Next Release Candidate

#978 Component/chip
  core/Sources/Components/Chip/View/SwiftUI/ChipView.swift
Labels: Next Release Candidate

#976 Component/progressbar
  core/Sources/Components/ProgressBar/View/SwiftUI/Public/ProgressBarDoubleView.swift
  core/Sources/Components/ProgressBar/View/SwiftUI/Public/ProgressBarView.swift
Labels: Next Release Candidate

#969 [RadioButton#968] Fix color.
  core/Sources/Components/RadioButton/UseCases/RadioButtonGetColorsUseCase.swift
  core/Sources/Components/RadioButton/UseCases/RadioButtonGetColorsUseCaseTests.swift
Labels: Next Release Candidate

#957 [CheckBox#949] Remove if view modifier.
  core/Sources/Components/Checkbox/View/SwiftUI/CheckboxGroupView.swift
  core/Sources/Components/Checkbox/View/SwiftUI/CheckboxView.swift
  core/Sources/Components/Checkbox/View/SwiftUI/CheckboxViewSnapshotTests.swift
Labels: Next Release Candidate

#977 Component/switch
  core/Sources/Components/Switch/View/SwiftUI/SwitchView.swift
Labels: Next Release Candidate

#971 [Tag#1939] Use default text font of tag if not overwritten by attribu…
  core/Sources/Components/Tag/View/UIKit/TagUIView.swift
  spark/Demo/Classes/View/Components/Tag/TagContent.swift
  spark/Demo/Classes/View/Components/Tag/UIKit/TagComponentUIViewModel.swift
Labels: Next Release Candidate

#882 [Accessibility] Updated progress bar accessibility
  core/Sources/Components/ProgressBar/AccessibilityIdentifier/ProgressBarAccessibilityIdentifier.swift
  core/Sources/Components/ProgressBar/View/SwiftUI/Internal/ProgressBarContentView.swift
  core/Sources/Components/ProgressBar/View/SwiftUI/Public/ProgressBarDoubleView.swift
  core/Sources/Components/ProgressBar/View/SwiftUI/Public/ProgressBarIndeterminateView.swift
  core/Sources/Components/ProgressBar/View/SwiftUI/Public/ProgressBarView.swift
  core/Sources/Components/ProgressBar/View/UIKit/ProgressBarUIView.swift
  core/Sources/Components/ProgressBar/View/UIKit/ProgressMainBarUIView.swift
Labels: Next Release Candidate

#981 980 bug textfield layering issue in swiftui
  core/Sources/Components/TextField/View/SwiftUI/TextFieldView.swift
  core/Sources/Components/TextField/View/SwiftUI/TextFieldViewInternal.swift
  core/Sources/Components/TextField/ViewModel/TextFieldViewModel.swift
  core/Sources/Components/TextField/ViewModel/TextFieldViewModelTests.swift
  spark/Demo/Classes/View/Components/Main/ComponentUIView.swift
Labels: Next Release Candidate
