Repository adevinta/spark-ios, pull requests merged in 2024-02, with the labels that each got.

#798 [ProgressTracker#790] Add user interactions
  core/Sources/Components/ProgressTracker/AccessibilityIdentifier/ProgressTrackerAccessibilityIdentifier.swift
  core/Sources/Components/ProgressTracker/AccessibilityIdentifier/ProgressTrackerAccessibilityIdentifierTests.swift
  core/Sources/Components/ProgressTracker/Enum/ProgressTrackerInteractionState.swift
  core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetColorsUseCase.swift
  core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetColorsUseCaseTests.swift
  core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetOutlinedColorsUseCase.swift
  core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetOutlinedColorsUseCaseTests.swift
  core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetTintedColorsUseCase.swift
  core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetTintedColorsUseCaseTests.swift
  core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetTrackColorUseCase.swift
  core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetTrackColorUseCaseTests.swift
  core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetVariantColorsUseCaseable.swift
  core/Sources/Components/ProgressTracker/View/ProgressTrackerIndicatorViewModel.swift
  core/Sources/Components/ProgressTracker/View/ProgressTrackerIndicatorViewModelTests.swift
  core/Sources/Components/ProgressTracker/View/ProgressTrackerTrackViewModel.swift
  core/Sources/Components/ProgressTracker/View/ProgressTrackerTrackViewModelTests.swift
  core/Sources/Components/ProgressTracker/View/ProgressTrackerViewModel.swift
  core/Sources/Components/ProgressTracker/View/ProgressTrackerViewModelTests.swift
  core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerContinuousUITouchHandlerTests.swift
  core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerDiscreteUITouchHandlerTests.swift
  core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerIndependentUITouchHandlerTests.swift
  core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerIndicatorUIControl.swift
  core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerTrackUIView.swift
  core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerUIControl.swift
  core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerUITouchHandler.swift
  core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerUITouchHandlerCreationTests.swift
  core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerUITouchHandlerTests.swift
  spark/Demo/Classes/View/Components/ProgressTracker/UIKit/ProgressTrackerComponentUIView.swift
  spark/Demo/Classes/View/Components/ProgressTracker/UIKit/ProgressTrackerComponentUIViewController.swift
  spark/Demo/Classes/View/Components/ProgressTracker/UIKit/ProgressTrackerComponentUIViewModel.swift
Labels: UIKit, Component

#804 [Checkbox#803] checked image color was fixed
  core/Sources/Components/Checkbox/UseCase/Colors/CheckboxColorsUseCase.swift
  core/Sources/Components/Checkbox/UseCase/Colors/CheckboxColorsUseCaseTests.swift
  core/Sources/Components/Checkbox/View/SwiftUI/CheckboxGroupViewSnapshotTests.swift
  core/Sources/Components/Checkbox/View/SwiftUI/CheckboxViewSnapshotTests.swift
  core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIView.swift
  core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIViewSnapshotTests.swift
Labels: ✅ Ready

#809 [checkbox#808] Add frozen tag to checkbox selection state enum
  core/Sources/Components/Checkbox/Enum/CheckboxSelectionState.swift
  spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroup/CheckboxGroupComponentUIView.swift
Labels: ✅ Ready, Next Release Candidate
